data = read.csv2("exdata-data-household_power_consumption/household_power_consumption.txt", skip = 66637, nrows = 2879, dec = ".", header = FALSE)
colnames(data) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
png("plot4.png")
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
with(data, plot(y = sapply(data["Global_active_power"], as.double), x = as.numeric(strptime(paste(as.character(data[["Date"]]), as.character(data[["Time"]])), format = "%d/%m/%Y %H:%M:%S")), main = "", xlab = "", ylab = "Global Active Power", type = "l", xaxt = "n"))
axis.POSIXct(1, at = c(as.POSIXct("2007-02-01 00:00:00"), as.POSIXct("2007-02-02 00:00:00"), as.POSIXct("2007-02-03 00:00:00")), format = "%a")
with(data, plot(y = sapply(data["Voltage"], as.double), x = as.numeric(strptime(paste(as.character(data[["Date"]]), as.character(data[["Time"]])), format = "%d/%m/%Y %H:%M:%S")), main = "", xlab = "datetime", ylab = "Voltage", type = "l", xaxt = "n"))
axis.POSIXct(1, at = c(as.POSIXct("2007-02-01 00:00:00"), as.POSIXct("2007-02-02 00:00:00"), as.POSIXct("2007-02-03 00:00:00")), format = "%a")
with(data, plot(range(as.numeric(strptime(paste(as.character(data[["Date"]]), as.character(data[["Time"]])), format = "%d/%m/%Y %H:%M:%S"))), range(data["Sub_metering_1"]), main = "", xlab = "", ylab = "Energy sub metering", xaxt = "n"))
axis.POSIXct(1, at = c(as.POSIXct("2007-02-01 00:00:00"), as.POSIXct("2007-02-02 00:00:00"), as.POSIXct("2007-02-03 00:00:00")), format = "%a")
with(data, lines(as.numeric(strptime(paste(as.character(data[["Date"]]), as.character(data[["Time"]])), format = "%d/%m/%Y %H:%M:%S")), data[["Sub_metering_1"]], type="S", col = "black"))
with(data, lines(as.numeric(strptime(paste(as.character(data[["Date"]]), as.character(data[["Time"]])), format = "%d/%m/%Y %H:%M:%S")), data[["Sub_metering_2"]], type="S", col = "red"))
with(data, lines(as.numeric(strptime(paste(as.character(data[["Date"]]), as.character(data[["Time"]])), format = "%d/%m/%Y %H:%M:%S")), data[["Sub_metering_3"]], type="S", col = "blue"))
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, cex = 1.0)
with(data, plot(y = sapply(data["Global_reactive_power"], as.double), x = as.numeric(strptime(paste(as.character(data[["Date"]]), as.character(data[["Time"]])), format = "%d/%m/%Y %H:%M:%S")), main = "", xlab = "datetime", ylab = "Global_reactive_power", type = "l", xaxt = "n"))
axis.POSIXct(1, at = c(as.POSIXct("2007-02-01 00:00:00"), as.POSIXct("2007-02-02 00:00:00"), as.POSIXct("2007-02-03 00:00:00")), format = "%a")
dev.off()